### ISSUE TITLE
Course, Exam-content api 이슈 존재

### ISSUE THREAD

**Issue by bayy1216** [Grading-X/Grading-X-BE#25]
## 개요
>
Coures 목록 보기 : course 1로 접속
 -> course1이 리스트로보여서 해당 클래스로 이동
-> 해당 exam은 권한이 없어 보이지 않음

course전체보기에서 권한이 없음에도 불구하고 course가 보이는 문제가 존재합니다
또한 시험상세보기에서 학생도 해당 시험을 조회할 권한이 없습니다

**Comment by sim-mer** [comment]
현재 mvp요구사항으로는 게스트만 시험보도록 하는 거라 교수자만 시험 조회를 허용하고 있습니다.

**Comment by bayy1216** [comment]
> 현재 mvp요구사항으로는 게스트만 시험보도록 하는 거라 교수자만 시험 조회를 허용하고 있습니다.

다른 사람 course도 보인다는 뜻입니다

**Comment by sim-mer** [comment]
> > 현재 mvp요구사항으로는 게스트만 시험보도록 하는 거라 교수자만 시험 조회를 허용하고 있습니다.
> 
> 다른 사람 course도 보인다는 뜻입니다

그러니까 제가 말한 부분은 course가 아니라 

> 시험상세보기에서 학생도 해당 시험을 조회할 권한이 없습니다 

이 부분입니다. course는 정민씨가 수정할거에요

**Comment by chaejm55** [comment]
course 권한 수정 및 수강생 변경(추가/삭제) 기능도 추가해서 pr 올렸습니다.
